---
apiVersion: argoproj.io/v1alpha1  # Changed from apps/v1
kind: Rollout                     # Changed from Deployment
metadata:
  name: example-spring-boot
  labels:
    app: example-spring-boot
spec:
  strategy:
    blueGreen: 
      activeService: example-spring-boot
      previewService: example-spring-boot-preview
      autoPromotionEnabled: false
  replicas: 1
  selector:
    matchLabels:
      app: example-spring-boot
  template:
    metadata:
      labels:
        app: example-spring-boot
    spec:
      containers:
        - name: example-spring-boot
          image: tsurankov/example-spring-boot-helloworld:1.0.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            failureThreshold: 3
            timeoutSeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            failureThreshold: 15
            timeoutSeconds: 5
            periodSeconds: 15
