---
apiVersion: argoproj.io/v1alpha1  # Changed from apps/v1
kind: Rollout                     # Changed from Deployment
metadata:
  name: appuio
  labels:
    app: appuio
spec:
  strategy:
    canary:                        # Changed from rollingUpdate or recreate
      steps:
      - setWeight: 20
      - pause: {}
  replicas: 2
  selector:
    matchLabels:
      app: appuio
  template:
    metadata:
      name: appuio
      labels:
        app: appuio
    spec:
      containers:
        - name: appuio
          image: appuio/example-spring-boot:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            failureThreshold: 3
            timeoutSeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            failureThreshold: 15
            timeoutSeconds: 5
            periodSeconds: 15
