---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appuio
spec:
  rules:
    - host: appuio-dev.local
      http:
        paths:
          - backend:
              service:
                name: appuio
                port:
                  number: 8080
            path: /
            pathType: Prefix
