---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-spring-boot
spec:
  strategy:
    blueGreen:
      activeService: example-spring-boot
      previewService: example-spring-boot-preview
      autoPromotionEnabled: true
  replicas: 1
  template:
    spec:
      containers:
        - name: example-spring-boot
          image: tsurankov/example-spring-boot-helloworld:1.2.0
